### GENERAL ###
CSV_PATH: "/srv/hdd2/javber/dataset.csv"
NUM_CLASSES: 2
EXPERIMENT_NAME: "custom_CNN_1"
FROM_CHECKPOINT: False
CHECKPOINT_PATH: False
NUM_WORKERS: 8

### TRAIN HPARAMS ###
BATCH_SIZE: 4
LEARNING_RATE: 0.001
SCHEDULER: "step"  # "step" o "plateau"
SCHEDULER_STEP: 5
SCHEDULER_REDUCTION: 0.99
NUM_EPOCHS: 100
OPTIMIZER: "adamw"
WEIGHT_DECAY: 0.0001
IMAGE_SIZE: 64
EARLY_STOPPING_PATIENCE: 2

### DATA AUGMENTATION ###
IMAGENET_MEAN: [0.485, 0.456, 0.406]
IMAGENET_STD: [0.229, 0.224, 0.225]
CROP_SCALE: [0.8, 1.0]  # Rango de escala para el recorte aleatorio
ROTATION_DEGREES: 15  # Rotación aleatoria en grados
HORIZONTAL_FLIP_PROB: 0.5  # Probabilidad de aplicar flip horizontal
BRIGHTNESS: 0.2
CONTRAST: 0.2
SATURATION: 0.2
HUE: 0.1

### CNN CONFIG ###
CNN_CONV_LAYERS: [[32, 3], [64, 3], [128, 3], [256, 3]]
CNN_DROPOUT_RATE: 0.5
CNN_USE_BATCHNORM: True
CNN_POOLING_TYPE: "max"
CNN_DENSE_NEURONS: 256